apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogapi-config
  namespace: catalogapi
  labels:
    app: catalogapi
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Port: "5672"
  RabbitMQ__Exchange: "order-placed-event"
  AuthService__BaseUrl: "http://users-api-service:8080"
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"
